"""The REPORT.md seal, and the lead prose it carries verbatim.

Survey block Q. `_seal_run_report` is what both F6 doors and both halt paths
run; `_carried_lead_prose` is why a regeneration does not silently delete the
prose GI-006 licenses the lead to append.
"""
from __future__ import annotations

from pathlib import Path

from foundry_mcp.schemas.vocab import (
    DEFECT_TIERS,
    REPORT_MD_FILENAME,
    TIER_UNKNOWN,
    defect_tier,
)
from foundry_mcp.tools.artifacts import _document_transaction
from foundry_mcp.tools.foundry_state import (
    blocking_defects,
    markdown_sections,
    now_iso,
    read_text_file,
)
from pathlib import Path






#: A generated REPORT.md header is a ``# `` title line and one banner sentence
#: naming the generator. Both are re-emitted fresh on every regeneration — the
#: banner carries the timestamp — so neither is ever carried over as prose.
#: Recognised by content rather than by position or line count so a change to
#: ``_render_markdown``'s header degrades to preserving a stale banner (visible,
#: and dropped again by the next seal) rather than to dropping lead prose.
_GENERATED_HEADER_MARKER = " by Foundry-Report."




def _lead_header_lines(header: list[str]) -> list[str]:
    """The lead's own lines from a REPORT.md header block."""
    return [
        line
        for line in header
        if line.strip()
        and not line.lstrip().startswith("# ")
        and _GENERATED_HEADER_MARKER not in line
    ]




#: The ONE section the seal appends, and the only place lead prose is written
#: back. Named "carried by the seal" so a reader knows the SEAL put the block
#: there rather than the lead putting it there themselves, and recognised again
#: on the next seal so a second terminal transition unwraps it instead of
#: wrapping the wrapper.
_LEAD_NOTES_HEADING = "## Lead notes (carried by the seal)"




def _carried_lead_prose(on_disk: str, generated: str) -> list[str]:
    """The on-disk lines that lie OUTSIDE the generated skeleton.

    The skeleton is the set of ``## `` headings the generator JUST WROTE, taken
    from the freshly generated document rather than from
    ``foundry_report._SECTION_TITLES`` — that table is a sibling casting's
    private name, and the document it just wrote is a better authority for what
    it generates than a constant this module would have to keep in step.

    So: the header's non-generated lines are the lead's; a block under a heading
    the generator did not write is the lead's, carried whole; a SECOND copy of a
    generated heading is the lead's, because the generator emits each exactly
    once; and a block under a generated heading is GENERATED and is carried
    NOWHERE. A previous seal's own ``_LEAD_NOTES_HEADING`` is unwrapped rather
    than re-wrapped, so sealing twice does not nest the wrapper twice.

    D-228 / D-230 — WHAT THE PREVIOUS ANSWER TO THIS QUESTION DID
    ------------------------------------------------------------
    This replaces ``_lead_only_lines`` + ``_merge_lead_prose``, which asked the
    question one rung finer: a line-granular ``difflib`` comparison of the
    on-disk section body against the freshly generated one, keeping the
    ``insert`` AND ``replace`` opcodes as "the lead's". A generated row whose
    VALUE moved between the two generations lands in a ``replace`` opcode, so
    the OLD row was kept and re-emitted as lead content. Driven at the real
    terminal doors: with ZERO prose appended and one ``Foundry-Spend`` recorded
    between the two generations, the HALTED transition returned
    ``lead_prose_lines: 11`` and said "11 line(s) of prose you appended were
    carried onto it (GI-006)", and the sealed REPORT.md carried a stale
    ``| GRIND cycles | 22 |  | 12 | 2 |`` directly below the fresh
    ``| GRIND cycles | 22 |  | 12 | 1 |``. The run's final artifact ended with
    two contradictory values for one question, and the operator was told they
    had authored the contradiction.

    THE FIX IS TO ASK A COARSER QUESTION, NOT A BETTER-TUNED ONE. Any rule that
    tells lead prose from generated prose by COMPARING VALUES re-acquires this
    defect the moment a value moves, because a moved value is indistinguishable
    from a line the lead typed. The heading is a seam nothing generated can
    cross: the generator writes exactly the headings in its published section
    list, so a block under one of them is generated by construction and no
    comparison is needed to know it.

    WHAT THAT COSTS, STATED (lead ruling, GRIND cycle 27). Prose typed INSIDE a
    generated section's body is no longer carried — it cannot be told from the
    body it sits in without the value comparison this defect is. GI-006's first
    clause is read as "appended prose survives the seal, in one appended
    section", not "the seal reconstructs the lead's edit positions". The lead
    appends under their own ``## `` heading, or above the first section, and the
    seal carries it verbatim.
    """
    old_header, old_blocks = markdown_sections(on_disk)
    _new_header, new_blocks = markdown_sections(generated)
    generated_headings = {heading for heading, _body in new_blocks}

    carried: list[str] = list(_lead_header_lines(old_header))
    seen: set[str] = set()
    for heading, body in old_blocks:
        if heading in generated_headings and heading not in seen:
            seen.add(heading)
            continue
        if heading == _LEAD_NOTES_HEADING:
            carried.extend(body)
            continue
        carried.extend([heading, *body])

    while carried and not carried[0].strip():
        carried.pop(0)
    while carried and not carried[-1].strip():
        carried.pop()
    return carried




def _seal_lead_prose(on_disk: str, generated: str) -> tuple[str, int]:
    """Append the lead's prose to the freshly generated REPORT.md, verbatim.

    Returns ``(sealed_text, carried_line_count)``. The count is 0 when the
    document on disk carried nothing outside the generated skeleton, and the
    caller then has nothing to write — a purely generated report is left EXACTLY
    as ``generate_report`` wrote it, which is the property that stops the seal
    growing the document one section per terminal transition.

    ONE TRAILING SECTION, AFTER EVERY GENERATED ONE. The prose does not go back
    where the lead put it: reconstructing an edit position needs a value
    comparison, and a value comparison is D-228 (see ``_carried_lead_prose``).
    Appended whole under ``_LEAD_NOTES_HEADING``, the carried block is
    unambiguous — every line in it is the lead's, and nothing generated is ever
    re-emitted as lead prose. GI-006's other clause is untouched: the generated
    sections are all present, in order, above it.
    """
    carried = _carried_lead_prose(on_disk, generated)
    if not carried:
        return generated, 0
    sealed = (
        generated.rstrip("\n")
        + "\n\n"
        + _LEAD_NOTES_HEADING
        + "\n\n"
        # NOT rstripped: `carried` has already lost its leading and trailing
        # BLANK lines, and stripping again here would eat trailing whitespace
        # off the lead's own last line. "Verbatim" is the whole promise.
        + "\n".join(carried)
        + "\n"
    )
    return sealed, len(carried)




def _generate_report(project_root: str, fdir: Path) -> dict:
    """C-10's ``generate_report`` \u2014 writes REPORT.md and report.json.

    fallout GI-033 / AC-061 / FR-063 (D-080) \u2014 THE SEAM LIVES WITH ITS
    CALLER NOW, AND THE CALLER IS LIFECYCLE.

    This function stood in `gates.py`, and this module imported it from there:
    a LIFECYCLE module reaching into the VERIFIER set to borrow a one-line
    wrapper around a lifecycle function. AC-061 refuses that direction with no
    exception, and the detour bought nothing \u2014 `foundry_report.py` is
    presentation, this module is presentation, and the edge between them has
    never been a crossing. `gates.py` no longer generates a report at all; what
    it still needs is `report_status`, which is a READ and is on its way to the
    leaf (concern C-060 row 2).

    STILL LAZY, and written ONCE per symbol, in the shape the shared pattern
    shows: `foundry_report` imports from this package, so a module-top import
    here closes a cycle that takes every tool in this server down at load.
    Unguarded, so a wiring break fails loudly at the one call site that needs
    the symbol rather than hiding behind a silent fallback.
    """
    from foundry_mcp.tools.foundry_report import generate_report

    return generate_report(Path(project_root), fdir)




def _regenerate_report_preserving_lead_prose(
    project_root: str, fdir: Path
) -> dict:
    """Regenerate the report without destroying what the lead appended to it.

    Returns ``{"report", "report_generated", "report_error", "lead_prose_lines",
    "lead_prose_error"}`` — never a refusal and never a raise.

    THE ONE REGENERATION BOTH TERMINAL TRANSITIONS RUN (D-224). ``done`` and
    ``nyquist_done`` reach it through ``_seal_run_report``; the cap reaches it
    through ``_halt_if_capped``. Writing the preservation once is the same
    argument D-043/D-044 made about the two F6 doors: a rule enforced at one
    terminal transition and not the other is a rule the run can walk around by
    ending the other way.

    A FAILURE TO PRESERVE IS RECORDED, NOT RAISED, AND NEVER COSTS THE REPORT.
    If the write-back fails, the freshly generated document stands and
    ``lead_prose_error`` says the prose could not be carried over — the caller
    puts that in the operator's message. The alternative, refusing the
    transition, would leave a run that has already passed every precondition
    unable to end.

    D-228 / D-230 — WHAT "PRESERVING" MEANS HERE, AFTER THE CYCLE-27 RULING.
    The carry is a SEAL, not a merge: ``_seal_lead_prose`` appends everything
    outside the generated skeleton into one trailing section and re-emits
    nothing generated. The difflib merge this used to run reported stale
    generated rows as "prose you appended" — with zero prose appended — and
    left the run's final artifact carrying two values for one question. Nothing
    below compares a generated line with anything.
    """
    # fallout GI-033 / AC-061 / FR-063 (D-080) — LAZY SEAM TO THE GENERATOR'S
    # OWN MODULE, NOT THROUGH THE VERIFIER SET.
    #
    # This reached `gates._generate_report`, which is itself a one-line lazy
    # wrapper over `foundry_report.generate_report` — so a LIFECYCLE module was
    # importing a VERIFIER one to borrow its wrapper around a lifecycle
    # function. AC-061 refuses that direction outright and the detour bought
    # nothing: `foundry_report.py` is lifecycle, this module is lifecycle, and
    # the edge between them has never been a crossing.
    #
    # STILL LAZY, for the reason the seam at the bottom of this file spells out:
    # `foundry_report` imports from this package, so a module-top import here
    # closes a cycle that takes every tool in the server down at once.
    md_path = fdir / REPORT_MD_FILENAME
    # BEFORE the generator runs, because the generator is what overwrites it.
    on_disk, _problem = read_text_file(md_path)

    report = _generate_report(project_root, fdir)
    report_ok = bool(report.get("ok"))
    report_error = "" if report_ok else str(
        report.get("error") or "the report generator returned no reason"
    )

    preserved = 0
    prose_error = ""
    if report_ok and on_disk.strip():
        fresh, fresh_problem = read_text_file(md_path)
        if fresh_problem is not None or not fresh.strip():
            prose_error = fresh_problem or (
                f"{REPORT_MD_FILENAME} carries no generated text to merge onto"
            )
        else:
            merged, preserved = _seal_lead_prose(on_disk, fresh)
            if preserved:
                try:
                    md_path.write_text(merged, encoding="utf-8")
                except OSError as exc:
                    prose_error = (
                        f"{preserved} line(s) of appended prose could not be "
                        f"written back to {REPORT_MD_FILENAME} "
                        f"({type(exc).__name__}: {exc})"
                    )
                    preserved = 0

    return {
        "report": report,
        "report_generated": report_ok,
        "report_error": report_error,
        "lead_prose_lines": preserved,
        "lead_prose_error": prose_error,
    }




def _seal_run_report(project_root: str, fdir: Path) -> dict:
    """Regenerate the report as PART of the F6 transition. D-218.

    Returns ``{"report", "report_generated", "report_error"}`` — never a
    refusal, and never a raise. Called by BOTH F6 doors, after the phase is
    written and before the run is archived.

    WHY THE TRANSITION WRITES IT (FR-001 / GI-006 / AC-036 / OT-025)
    ---------------------------------------------------------------
    `_done_preconditions` asks whether a report EXISTS carrying every section
    — that is exactly what GI-006 makes a precondition of DONE, and it is all
    `report_status` can answer — and nothing asked whether the document
    described the run it was closing. Driven end to end through the real
    handlers: at F5.5 with both requirements VERIFIED and defects.json empty,
    `generate_report` wrote `latent_backlog {"open_count": 0, "defects": []}`;
    one open LATENT D-001 was then filed, and `foundry_mark_phase_complete(
    'done')` returned ok True, phase F6, with its own checklist reading
    `zero_blocking_defects (live=0 unknown_tier=0 latent_backlog=1)` beside
    `report_generated (missing_sections=0)`. The run reached F6 with a report
    whose LATENT backlog was empty while a LATENT defect was open — against
    FR-001 ("open LATENT instances go to the F6 named backlog") and against
    `_blocking_defects`' own hint, which promises the operator those defects are
    "named in the F6 backlog".

    THE MECHANISM ALREADY EXISTED AT THE OTHER TERMINAL TRANSITION.
    `_halt_if_capped` generates the report as part of the HALTED transition,
    "rather than left to the lead, because a halted run whose open work was
    never written down is the outcome the cap is supposed to prevent". DONE has
    the same property and did not do it. This is that block, in the shape the
    two doors can share: generated AFTER `_update_phase(fdir, "F6")` so the
    document renders the FINISHED run (`report.json`'s `run.phase`), and a
    generator failure recorded in a second short transaction because
    `_document_transaction` is an fcntl-locked critical section that must not
    be held across the generator.

    WHY THE GATE IS NOT ALSO GIVEN A STALENESS CHECK. Currency is not a
    question `report_status` can answer, and the two ways to make it one are
    both worse than writing the document. Comparing `generated_at` against
    ledger mtimes makes the terminal door depend on filesystem timestamps and
    can fail to terminate — one `Foundry-Spend` between `Foundry-Report` and
    `Foundry-Phase('done')` would refuse the run again, for a report that is
    correct about every fact the gate reads. Re-deriving the sections inside
    the gate is `generate_report` re-implemented inside this module, which is
    the second copy this casting is forbidden to write. Leaving the gate as it
    is also keeps the property `_done_preconditions` exists for: both F6 gates
    and both F6 transitions consult ONE evaluation and cannot disagree about
    what "done" means (D-037 / D-043 / D-044). What the transition adds is not
    a check — it is the artifact.

    A GENERATOR FAILURE DOES NOT REFUSE, for `_halt_if_capped`'s reason. The
    preconditions have already passed, F6 is written, and DONE has no exit; a
    refusal after the phase write would leave the run unable to be anything.
    The failure is RECORDED in `state.json` under `done_report_error` and SAID
    in the message, naming the one call that still writes the report. GI-006's
    refusal condition is ABSENCE, and that stays enforced where it belongs, in
    `_done_preconditions`, before this runs at all.

    D-224 — AND IT REGENERATES WITHOUT DESTROYING THE OTHER HALF OF GI-006.
    ----------------------------------------------------------------------
    GI-006 is two clauses. This function was written to enforce the second
    ("`Foundry-Phase('done')` refuses if the report is absent") and, for one
    cycle, enforced it by destroying the first ("the lead may append prose"):
    the regeneration below overwrote REPORT.md whole, `clear_active_run()` ran
    immediately after, and the run was archived with the lead's prose gone and
    nothing in the response saying so. Driven: a `## Lead notes` section
    carrying a sentinel, appended below the generated sections, was absent from
    disk after `Foundry-Phase('done')` returned ok True and phase F6.

    Both clauses now hold, and neither is traded for the other:
    `_regenerate_report_preserving_lead_prose` writes the fresh document and
    carries the lead's additions back onto it, and `_sealed_report_sentence`
    says how many lines it carried.
    """
    sealed = _regenerate_report_preserving_lead_prose(project_root, fdir)
    if not sealed["report_generated"]:
        with _document_transaction(fdir / "state.json") as doc:
            doc["done_report_error"] = sealed["report_error"]
            doc["updated_at"] = now_iso()
    return sealed




def _sealed_report_sentence(sealed: dict, fdir: Path) -> str:
    """The one spelling of what the F6 message says about the report.

    Both F6 doors say it, so it is written once — the drift between the `done`
    and `nyquist_done` branches is the shape D-043 and D-044 were filed for.
    Names the LATENT backlog count because that is the fact FR-001 puts in the
    report and the fact a stale report got wrong.
    """
    # fallout GI-033 / AC-061 (D-080, concern C-059) — THE FACTS COME OFF THE
    # LEAF, AND THE SENTENCE STAYS WITH WHOEVER SPEAKS IT.
    #
    # This reached `gates._blocking_defects`, a LIFECYCLE module importing a
    # VERIFIER one, which AC-061 refuses with no exception at all. Casting 10
    # hoisted the READ to `foundry_state.blocking_defects` as a pure counter —
    # facts only, no reason and no hint — because the refusal PROSE is
    # lifecycle knowledge and belongs where the refusal is spoken. This module
    # needs only the count, so it takes the numbers and crosses nothing.
    if not sealed["report_generated"]:
        return (
            "The report could NOT be regenerated at F6: "
            f"{sealed['report_error']}. The document on disk therefore predates "
            "this transition — repair what the error names and call "
            "Foundry-Report, which is not a phase transition and still runs."
        )
    latent = blocking_defects(
        fdir, tiers=DEFECT_TIERS, unknown_tier=TIER_UNKNOWN, tier_of=defect_tier
    )["latent"]
    sentence = (
        f"The report was regenerated as part of this transition, naming "
        f"{len(latent)} open LATENT defect(s) in the F6 backlog"
        + (f": {', '.join(latent)}." if latent else ".")
    )
    return sentence + _lead_prose_clause(sealed)




def _lead_prose_clause(sealed: dict) -> str:
    """What a sealing transition says about the lead's own prose. One spelling.

    Returns "" when there was no prose and no failure — the only state in which
    there is nothing to report — otherwise a clause beginning with a space,
    ready to append to whatever sentence the calling door builds around it.

    D-224 / GI-006: a regeneration that moved the lead's own prose SAYS so. The
    failure this closes was silent on both halves — the prose went and the
    response did not mention it — so the outcome is reported either way rather
    than only when it went wrong.

    D-228 / D-230: and it says it ONLY when there was prose. The sentence used
    to fire on the difflib merge's count, which counted stale generated rows, so
    a run whose lead appended nothing was told it had appended eleven lines. The
    count comes off `_seal_lead_prose`, which counts only what lies outside the
    generated skeleton, and it names the section the block was carried into so
    the operator can find it.

    D-233 — AND IT IS A FUNCTION BECAUSE THE THIRD TERMINAL DOOR SAID NEITHER.
    -------------------------------------------------------------------------
    These two clauses lived inside `_sealed_report_sentence`, which has exactly
    two callers, both F6 doors. `_halt_if_capped` runs the SAME
    `_regenerate_report_preserving_lead_prose` and publishes the same
    `lead_prose_lines` / `lead_prose_error` as result fields, but built its
    operator-facing `message` independently — so the cap sealed the lead's prose
    and never said so, and a FAILED write-back got no "WARNING:" at all. That is
    D-224's silence verbatim, at the other terminal door, and it is the shape
    D-043 / D-044 named: a rule enforced at one terminal transition and not the
    other is a rule the run walks around by ending the other way. HALTED is
    reachable from `grind_start` and `assay_fail`, and `display.py` renders a
    phase result's `message` and nothing else, so the message was the whole of
    what an operator would ever see.

    Extracted rather than sharing the whole sentence: `_sealed_report_sentence`
    speaks of "F6" and "the F6 backlog", which a HALTED run never reaches, and
    it names the LATENT count the cap's own message already names. Two doors
    with two accurate framings and ONE spelling of the facts they share.
    """
    if sealed.get("lead_prose_error"):
        return f" WARNING: {sealed['lead_prose_error']}"
    if sealed.get("lead_prose_lines"):
        return (
            f" {sealed['lead_prose_lines']} line(s) of prose you appended were "
            f"carried onto it verbatim, under `{_LEAD_NOTES_HEADING}` "
            "(GI-006)."
        )
    return ""
