"""The rules `router_revert_report` reverts one at a time, as data.

lead-stalls GI-008 / FR-008 / OT-002 — A TABLE CANNOT LIVE IN THE FILE IT
MUTATES.
------------------------------------------------------------------------
Four of these rows revert text in `test_guidance_imperatives.py` itself, and
every row stores that text verbatim. Kept in that module, each such row would
appear in the file twice — once as the rule and once as the row quoting it —
so `text.count(old) == 1` fails and the revert could not be applied at all.
The rows therefore live in their own module, which `_run_with` copies into the
tree unchanged while writing only the one file under mutation.

Each row is ``(name, file, the text as it stands, the text it reverts to)``.
The name is what the evidence log prints; the order is the order the log walks.
"""
from __future__ import annotations

_GUIDANCE_REL = "src/foundry_mcp/tools/orchestration/guidance.py"
_THIS_MODULE = "tests/orchestration/test_guidance_imperatives.py"
_TEAMS_REL = "src/foundry_mcp/tools/orchestration/teams.py"
_TRANSITIONS_REL = "src/foundry_mcp/tools/orchestration/transitions.py"


_ROUTER_REVERTS = (
    ('team-arm', _GUIDANCE_REL,
     'and not _team_work_in_flight(',
     'and not (lambda *a, **k: False)('),
    ('f3-live-arm', _GUIDANCE_REL,
     'if open_count > 0 or grind_live:',
     'if open_count > 0:'),
    ('acceptance-reader', _GUIDANCE_REL,
     'if done_at is not None:',
     'if False:'),
    ('notice-gate', _GUIDANCE_REL,
     'told_to_wait = (',
     'told_to_wait = True or ('),
    ('in-flight-unmeasured', _GUIDANCE_REL,
     'or pending < 1:\n        return True',
     'or pending < 1:\n        return False'),
    ('refusal-one-branch', _GUIDANCE_REL,
     'else "redispatch"\n        )',
     'else "refused"\n        )'),
    ('streams-context', _GUIDANCE_REL,
     'not the live tree."\n                    + _BRANCHED_ACTION_CONTEXT',
     'not the live tree. Spawn agents using the agent_configs below."'),
    ('refusal-boundary', _GUIDANCE_REL,
     'refused_at >= finished_at',
     'refused_at > finished_at'),
    ('casting-slot-last', _GUIDANCE_REL,
     'return ids[0]',
     'return ids[-1]'),
    ('casting-slot-order', _GUIDANCE_REL,
     'for key in ("cast_refused", "cast_unaccepted"):',
     'for key in ("cast_unaccepted", "cast_refused"):'),
    ('condition-detector', _THIS_MODULE,
     '(?:if|unless|when|whenever|only|once|in case|should|whether|depending)',
     '(?:NEVERMATCHES)'),
    ('in-flight-redispatch', _GUIDANCE_REL,
     '("refused", "redispatch", "unaccepted")',
     '("refused", "unaccepted")'),
    ('one-scan', _GUIDANCE_REL,
     '_waiting_on_agents(project_root, teams=teams)',
     '_waiting_on_agents(project_root)'),
    ('refusal-own-team', _GUIDANCE_REL,
     'if isinstance(own, str) and isinstance(registered, list)\n            and own in registered',
     'if row.get("teams_active") is True'),
    ('context-structure', _THIS_MODULE,
     'if lowered in _CLAUSE_OPENERS:',
     'if True:'),
    ('refusal-vocabulary', _THIS_MODULE,
     'r"|refused|refuses|rejected|rejects|errors|errored|ok (?:False|True)"\n',
     ''),
    ('condition-structure', _THIS_MODULE,
     '_EARLIER_CALL = r"',
     '_EARLIER_CALL = r"NEVERMATCHES'),
    ('sentence-anchor', _THIS_MODULE,
     '(?:^|(?<=[.!?:])[ \\t]+)\\s*(?:[-*',
     '^\\s*(?:[-*'),
    ('choice-shape', _THIS_MODULE,
     'if _offers_a_choice(sentence):',
     'if False:'),
    ('refused-first', _GUIDANCE_REL,
     'if refused and refused[0] in',
     'if refused and refused[-1] in'),
    ('live-teams-registered', _GUIDANCE_REL,
     '"teams_registered": teams_registered,\n',
     ''),
    ('streams-branch', _GUIDANCE_REL,
     '        "live": _STREAMS_RUNNING,\n',
     ''),
    ('spawn-order', _GUIDANCE_REL,
     '        blocks=_SPAWN_PROMPT_ORDER[phase],\n',
     '        blocks=("dispatch",),\n'),
    ('standing-rule', _GUIDANCE_REL,
     '    + " GRIND: "\n    + _spawn_prompt(_SPAWN_PROMPT_ORDER["grind"])\n',
     ''),
    ('grind-order', _GUIDANCE_REL,
     '"dispatch", "grind_cycle_context", "defects", "alignment_block",\n        "progress_protocol",\n',
     '"dispatch", "grind_cycle_context", "defects", "alignment_block",\n'),
    ('run-streams-sentence', _GUIDANCE_REL,
     '"own record is in that list, because its own re-run is the one "\n            "thing that records it. ',
     '"own record is a finding. If an AGENT stream finished and no record "\n            "exists, re-dispatch it, or file it. '),
    ('one-move-rule', _GUIDANCE_REL,
     '    + _SPAWN_PROMPT_RULE + " " + _SPAWN_IS_ONE_MOVE\n',
     '    + _SPAWN_PROMPT_RULE\n'),
    ('one-move-step', _GUIDANCE_REL,
     '        note=_SPAWN_IS_ONE_MOVE + " " + _MODEL_CLAUSE.format(door=door),\n',
     '        note=_MODEL_CLAUSE.format(door=door),\n'),
    ('one-step-clause', _GUIDANCE_REL,
     '    + " A spawn door and the Agent call it feeds are one step of that move "\n    "(the spawn rule below)."\n',
     ''),
    ('dispatch-yield', _GUIDANCE_REL,
     '        _CAST_WAVE_SPAWN,\n        _YIELD,\n    ),\n    "Wave {wave}',
     '        _CAST_WAVE_SPAWN,\n    ),\n    "Wave {wave}'),
    ('seed-running', _GUIDANCE_REL,
     '    "A teammate whose ledger holds only the line its spawn door wrote counts "\n    "as running, because the door and its Agent call are one move. "\n',
     '    ""\n'),
    ('stale-seed', _GUIDANCE_REL,
     '"has cost one call, and the dispatch still begins at step (3). A wave "\n    "whose door already returned reads here only once its seeds are stale — "\n    "no teammate wrote a line in the stall window — and that wave is "\n    "dispatched again.",',
     '"has cost one call, and the dispatch still begins at step (3).",'),
    ('stream-call', _GUIDANCE_REL,
     'agents = [_stream_agent_step(name) for name in names if name != "sight"]',
     'agents = [_stream_agent_step(name) for name in names if name not in ("sight", "test01")]'),
    ('stream-config', _GUIDANCE_REL,
     '                            if stream not in ("trace", "prove", "test", "sight")\n',
     '                            if False\n'),
    ('stream-yield', _GUIDANCE_REL,
     '    if agents:\n        steps.append(_YIELD)\n',
     ''),
    ('stream-snapshot', _GUIDANCE_REL,
     '    "every finding against `git archive HEAD` rather than the live tree, and "\n    "cite that sha in your report."\n',
     '    "every finding."\n'),
    ('stream-model', _GUIDANCE_REL,
     '        f"{model}subagent_type=\'{subagent_type}\', run_in_background=true, "\n',
     '        f"subagent_type=\'{subagent_type}\', run_in_background=true, "\n'),
    ('next-calls', _GUIDANCE_REL,
     '        result["next_calls"] = [_call_record(step) for step in next_calls]\n',
     '        pass\n'),
    ('yield-render', _GUIDANCE_REL,
     '    if step.tool == _END_TURN:\n        return _WAITING_IS_NOT_STOPPING\n',
     ''),
    ('castings-taskoutput', _GUIDANCE_REL,
     '"TeamCreate ceremony is skipped. Its return message is its TaskOutput, "',
     '"TeamCreate ceremony is skipped. Its return message is its TaskOutput(task_id), "'),
    ('validate-step', _GUIDANCE_REL,
     '            _Step(\n                "Foundry-Validate-Castings",\n                note="the check of what the decomposition wrote",\n            ),\n',
     ''),
    ('assay-gate', _GUIDANCE_REL,
     '            _Step("Foundry-Gate", "phase=\'assay\'"),\n',
     '            _Step("Update state to F4"),\n'),
    ('done-commit', _GUIDANCE_REL,
     '            _Step(\n                "Bash",\n                "command=\'git commit -m \\"chore: strip the evidence corpus\\"\'",\n                note="commits the strip.",\n            ),\n',
     ''),
    ('audit-structure', _THIS_MODULE,
     '    findings.extend(audit_next_call_structure(drives))\n',
     ''),
    ('audit-spawns', _THIS_MODULE,
     '    if spawns:\n        if _SPAWN_IS_ONE_MOVE not in rule:',
     '    if False:\n        if _SPAWN_IS_ONE_MOVE not in rule:'),
    ('audit-roster', _THIS_MODULE,
     '    if action == "run_streams" and steps:\n',
     '    if False:\n'),
    ('audit-fresh-seed', _THIS_MODULE,
     '    ("cast-dispatched-fresh-seed", "ST-001", _arrange_cast_dispatched_fresh_seed, "build_castings", "live"),\n',
     ''),
    ('audit-call-prose', _THIS_MODULE,
     '    r"\\b(Foundry-[A-Z]',
     '    r"\\bNEVERMATCHES(Foundry-[A-Z]'),
    ('list-move-rule', _GUIDANCE_REL,
     '    "\\n- NEVER stop between phases. " + _A_SERVED_LIST_IS_ONE_MOVE\n    + " The one Foundry-Next a list tolerates between two of its steps is "\n    "the gate-then-phase read: " + _GATE_THEN_PHASE_EXCEPTION\n    + " Skipping it there is correct and is not a shortcut."\n',
     '    "\\n- NEVER stop between phases. Call Foundry-Next after each step and "\n    "follow it; a spawn door and the Agent call it feeds are one step (the "\n    "spawn rule below). REQUIRED everywhere except exactly one place: "\n    + _GATE_THEN_PHASE_EXCEPTION\n    + " Skipping it there is correct and is not a shortcut; skipping it "\n    "anywhere else is."\n'),
    ('gate-read', _GUIDANCE_REL,
     '    "Foundry-Next straight after a passing Foundry-Gate is OPTIONAL — the "\n    "gate no longer consumes the ordering token, so the list\'s Foundry-Phase "\n    "is accepted without it. It is a read and not a move: that is where the "\n    "INSPECT mode (its width) and the rule that fired are announced, its "\n    "answer never replaces the list you are making, and the step after it is "\n    "still the step your list numbers after that Foundry-Gate. Never call it "\n    "to satisfy the protocol."\n',
     '    "Foundry-Next between a passing Foundry-Gate and its Foundry-Phase is "\n    "OPTIONAL — the gate no longer consumes the ordering token, so "\n    "Foundry-Phase straight after a passing Foundry-Gate is accepted. That is "\n    "where the INSPECT mode (its width) and the rule that fired are announced, "\n    "so call it there when you want them; never call it to satisfy the "\n    "protocol."\n'),
    ('gate-note-claim', _GUIDANCE_REL,
     '    "Foundry-Next straight after a passing Foundry-Gate is OPTIONAL — the "\n    "gate no longer consumes the ordering token, so the list\'s Foundry-Phase "\n    "is accepted without it. It is a read and not a move: that is where the "\n    "INSPECT mode (its width) and the rule that fired are announced, its "\n    "answer never replaces the list you are making, and the step after it is "\n    "still the step your list numbers after that Foundry-Gate. Never call it "\n    "to satisfy the protocol."\n',
     '    "Foundry-Next between a passing Foundry-Gate and its Foundry-Phase is "\n    "OPTIONAL — the gate no longer consumes the ordering token, so "\n    "Foundry-Phase straight after a passing Foundry-Gate is accepted. It is a "\n    "read and not a move: that is where the INSPECT mode (its width) and the "\n    "rule that fired are announced, its answer never replaces the list you "\n    "are making, and the step after it is still that list\'s Foundry-Phase. "\n    "Never call it to satisfy the protocol."\n'),
    ('advance-notice', _GUIDANCE_REL,
     '        gate_advance_note = _gate_advance_notice(gate_advance_note, next_calls)\n',
     '        gate_advance_note = (\n            f"✅ Foundry-Gate(phase=\'{gate_advance_note}\') ALREADY PASSED — do NOT re-run it. "\n            "Proceed directly to the transition step (Foundry-Phase / state update) in the imperative below."\n        )\n'),
    ('deliberate-line', _GUIDANCE_REL,
     '    "\\n- NEVER deliberate for more than 30 seconds between tool calls. If you "\n    "catch yourself thinking, make the next step of the list you were served, "\n    "and call Foundry-Next after its last step."\n',
     '    "\\n- NEVER deliberate for more than 30 seconds between tool calls. If you catch yourself thinking, call Foundry-Next and execute whatever it says."\n'),
    ('team-down-answer', _TEAMS_REL,
     '"next_call": TEAM_DOWN_NEXT_CALL,',
     '"next_call": "Call Foundry-Next now.",'),
    ('crossing-fallback', _GUIDANCE_REL,
     '    if "{gate}" in header or "{token}" in header:\n        return None, _generic_header(action)\n',
     ''),
    ('audit-one-move', _THIS_MODULE,
     '    for number, step in enumerate(steps[:-1], 1):\n        if step.tool == "Foundry-Next":',
     '    for number, step in enumerate(steps[:0], 1):\n        if step.tool == "Foundry-Next":'),
    ('audit-answers', _THIS_MODULE,
     '            and steps[number].tool != "Foundry-Next"\n',
     '            and False\n'),
    ('audit-rules-walk', _THIS_MODULE,
     '        for sentence in _orders_foundry_next_mid_list(rules):\n',
     '        for sentence in _orders_foundry_next_mid_list(""):\n'),
    ('f5-crossing', _GUIDANCE_REL,
     '        crossing = _post_assay_crossing(\n            fdir, "F5", "TEMPER", gate, GRIND_AGENT_CONFIG,\n        )\n        if crossing is not None:\n            return crossing\n',
     ''),
    ('f55-crossing', _GUIDANCE_REL,
     '        crossing = _post_assay_crossing(\n            fdir, "F5.5", "NYQUIST", "done", GRIND_AGENT_CONFIG,\n        )\n        if crossing is not None:\n            return crossing\n',
     ''),
    ('temper-gate-step', _GUIDANCE_REL,
     '            _Step(\n                "Foundry-Gate", "phase=\'{gate}\'",\n',
     '            _Step(\n                "Foundry-Report",\n'),
    ('nyquist-gate-step', _GUIDANCE_REL,
     '            _Step(\n                "Foundry-Gate", "phase=\'done\'",\n                note=(\n                    "the gate out of F5.5.',
     '            _Step(\n                "Foundry-Report",\n                note=(\n                    "the gate out of F5.5.'),
    ('grind-first', _GUIDANCE_REL,
     '    if blocking["blocking"] > 0:\n        seals = _grind_start_seals(fdir)\n',
     '    if False:\n        seals = _grind_start_seals(fdir)\n'),
    ('gate-record', _GUIDANCE_REL,
     '    if passed != gate:\n        return None',
     '    if passed is None:\n        return None'),
    ('details-crossing', _GUIDANCE_REL,
     '        or (details or {}).get("crossing")\n',
     ''),
    ('temper-context', _GUIDANCE_REL,
     '                f"gate out of F5, `{gate}`, and the next Foundry-Next reads "\n',
     '                f"gate out of F5. When clean, call Foundry-Gate(phase=\'{gate}\'). "\n'),
    ('post-assay-states', _THIS_MODULE,
     '    ("temper-owed", "GI-008", _arrange_temper_owed, "run_temper", None),\n',
     ''),
    ('held-full-reopen', _GUIDANCE_REL,
     '        if delta or still:\n',
     '        if delta:\n'),
    ('held-reopen-reason', _GUIDANCE_REL,
     '                        if delta else _HELD_CLASS_REOPEN\n',
     '                        if delta else ""\n'),
    ('held-closing', _GUIDANCE_REL,
     '            "accepted from a clean FULL F2 and not from past ASSAY. The "\n',
     '            "accepted nowhere: a FULL INSPECT has nothing to widen. The "\n'),
    ('f4-grind', _GUIDANCE_REL,
     '        grind = _blocking_grind_crossing(\n            "F4", "ASSAY", blocking, GRIND_AGENT_CONFIG, fdir,\n        )\n        if grind is not None:\n            return grind\n',
     ''),
    ('f4-filed-states', _THIS_MODULE,
     '    ("assay-passed-filed", "GI-008", _arrange_assay_passed_filed, "transition_to_grind", None),\n',
     ''),
    ('f4-short', _GUIDANCE_REL,
     '        short = _short_ledger_assay(fdir, project_root, state, "F4")\n'
     '        if short is not None:\n            return short\n',
     ''),
    ('short-states', _THIS_MODULE,
     '    ("assay-short", "GI-008", _arrange_assay_short, "run_assay", None),\n',
     ''),
    ('cap-slot', _GUIDANCE_REL,
     '        seals = not template and details.get("seals_halted") is True\n',
     '        seals = False\n'),
    ('capped-states', _THIS_MODULE,
     '    ("assay-passed-filed-capped", "GI-008", _arrange_assay_passed_filed_capped, "transition_to_grind", None),\n',
     ''),
    ('seal-detector', _THIS_MODULE,
     '    if capped:\n        for number, step in enumerate(steps[:-1], 1):',
     '    if False:\n        for number, step in enumerate(steps[:-1], 1):'),
    ('temper-coverage', _TRANSITIONS_REL,
     '    _ledger_coverage_rung(ladder, checklist, fdir, project_root, "TEMPER")\n',
     ''),
    ('nyquist-coverage', _TRANSITIONS_REL,
     '    _ledger_coverage_rung(ladder, checklist, fdir, project_root, "NYQUIST")\n',
     ''),
    ('unrecorded-reopen', _TRANSITIONS_REL,
     '        reopenable = (\n            recorded_width == "DELTA" or bool(held) or unrecorded_width\n        )\n',
     '        reopenable = recorded_width == "DELTA" or bool(held)\n'),
    ('f5-short', _GUIDANCE_REL,
     '        short = _short_ledger_assay(fdir, project_root, state, "F5")\n        if short is not None:\n            return short\n',
     ''),
    ('f55-short', _GUIDANCE_REL,
     '        short = _short_ledger_assay(fdir, project_root, state, "F5.5")\n        if short is not None:\n            return short\n',
     ''),
    ('width-grind-branch', _GUIDANCE_REL,
     '            if open_count == 0:\n',
     '            if True:\n'),
    ('none-owed', _THIS_MODULE,
     '        elif names_no_call and not _none_is_owed(action, owed):\n',
     '        elif False:\n'),
    ('head-gate-walk', _THIS_MODULE,
     '        head_gate = d.get("head_gate")\n',
     '        head_gate = None\n'),
    ('short-phase-states', _THIS_MODULE,
     '    ("temper-short", "GI-008", _arrange_temper_short, "run_assay", None),\n',
     ''),
    # lead-stalls GI-008 / OT-013 (D-069) — THE CLAUSE, NOT ITS CALL SITES.
    # The three rows above revert where `_short_ledger_assay` is ASKED; this
    # one reverts what it SAYS. cbd1500 made the closing clause conditional so
    # the sentence says nothing at F4 it has not earned, and reverted alone
    # the whole suite stayed byte-identically green — 5765 passed, 88 skipped,
    # the shipped control's own counts. A zero over 86 rules none of which is
    # this sentence is a zero over a population the change is not in.
    ('short-ledger-earned', _GUIDANCE_REL,
     '            + ("." if phase == "F4" else f" — from {phase} as surely as from F4.")\n',
     '            + f" — from {phase} as surely as from F4."\n'),
    # lead-stalls D-080 — the two clauses of the D-079 auditor call that no
    # test held: M7 (the Cap item) and M8 (the one-message fan-out).
    ('nyquist-cap', _GUIDANCE_REL,
     'f"IDs: {\', \'.join(row)}. Cap: {_NYQUIST_BATCH_SIZE}. Result file: "',
     'f"IDs: {\', \'.join(row)}. Result file: "'),
    ('nyquist-parallel', _GUIDANCE_REL,
     '                f"for batch {number} of {len(rows)}, every batch\'s call in "\n                "ONE parallel message"\n',
     '                f"for batch {number} of {len(rows)}, every batch\'s call in "\n                "its own message"\n'),
    # lead-stalls D-081 — the auditor's result file, the reading of it, and
    # the filing it is served: each one on its own.
    ('nyquist-result-file', _GUIDANCE_REL,
     '. Result file: "\n            f"{result_file(number)} — write the JSON summary your Output "\n            "section defines there before you return it; it is the one record "\n            "of your escalations this server reads.\\""',
     '.\\""'),
    ('nyquist-escalation-arm', _GUIDANCE_REL,
     '        escalated = _nyquist_escalation_crossing(\n            fdir, blocking, GRIND_AGENT_CONFIG,\n        )\n        if escalated is not None:\n            return escalated\n',
     ''),
    ('escalation-filing-slot', _GUIDANCE_REL,
     '            _Step(_EACH_UNFILED_ESCALATION),\n',
     ''),
    ('impl-bug-only', _GUIDANCE_REL,
     'row.get("reason") != "ESCALATE_IMPL_BUG"',
     'not str(row.get("reason", "")).startswith("ESCALATE_")'),
    ('escalation-carried', _GUIDANCE_REL,
     '        if rid not in carried\n',
     ''),
    ('escalation-this-cycle', _GUIDANCE_REL,
     '_nyquist_escalations(fdir, current_cycle(fdir), batches)',
     '_nyquist_escalations(fdir, 0, batches)'),
    # lead-stalls D-082 — the decomposer's literal prompt, and what the F0
    # arm publishes for it.
    ('decomposer-spec', _GUIDANCE_REL,
     'f"foundry-archive/{{run}}/, from the spec at {spec}: follow the "',
     '"foundry-archive/{run}/, from the spec at <the run\'s spec path>: follow the "'),
    ('decompose-dispatch', _GUIDANCE_REL,
     '                    **_decompose_dispatch(project_root, fdir, state),\n',
     ''),
    # lead-stalls D-081 / D-082 — the instrument: the narrowed placeholder,
    # the count rung, the result rung, and the walk that models only what an
    # agent can do.
    ('prompt-arg-narrow', _THIS_MODULE,
     "|<[^>]*\\breturned\\b[^>]*\\bverbatim\\b[^>]*>)",
     "|<[^>]+>)"),
    ('count-rung', _THIS_MODULE,
     '            and _COUNT_HANDED_OVER.search(step.each)\n',
     '            and False\n'),
    ('result-rung', _THIS_MODULE,
     '            agent and agent.group(1) in _DOORLESS_AGENTS\n',
     '            False\n'),
    ('honest-walk', _THIS_MODULE,
     '                if agent and agent.group(1) in _DOORLESS_AGENTS:\n                    _write_escalation(root, args)\n',
     '                if False:\n                    _write_escalation(root, args)\n'),
)
